name: Hello World
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - type: uses
        name: Check out repository code
        uses: actions/checkout@v2
      - type: run
        name: Run a one-line script
        run: echo Hello, world!
